server:
  port: 8002

mybatis:
  mapperLocations: classpath:mybatis/*-mapper.xml
  config: classpath:mybatis/mybatis-conf.xml
  typeAliasesPackage: com.mop
  checkConfigLocation: false

#Prod
spring:
  datasource:
    url: jdbc:mysql://172.31.65.110:3306/app_test_data?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: xm_test_data_dev
    password: cNaNCW4vEruhXrK8OXBSWmmCc
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    test-while-borrow: true
    validation-query: SELECT 1 FROM log_center_test_testresult
    time-between-evication-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000
  http:
    multipart:
      maxFileSize: 300MB
      maxRequestSize: 150MB
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  mvc:
    async:
      request-timeout: 3600000
  thymeleaf:
    #缓冲的配置
    cache: false
    check-template: true
    check-template-location: true
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  resource:
